Repository HYF-Class20/agile-development-group5-all-about-trees, pull requests merged in 2023-04, with the labels that each got.

#8 updating communication-plan
  planning/README.md
  planning/communication.md
  planning/constraints.md
  planning/user-personas.md
Labels: documentation, .md

#4 3 brainstorming
  planning/README.md
  planning/constraints.md
  planning/user-personas.md
Labels: check-in

#12 lint:md problem solved
  planning/constraints.md
Labels: check-in

#16 updated backlog md file
  planning/backlog.md
Labels: check-in

#10 add user personas detals
  planning/README.md
  planning/user-personas.md
Labels: .md

#19 add Retrospective details
  planning/retrospective.md
Labels: .md

#21 run spell-check
  planning/backlog.md
Labels: group 5, backlog.md
